config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :stores do
      resources :working_days, only: [:index, :create, :edit, :destroy] do
        resources :working_hours, only: [:create, :destroy, :update]
      end
    end
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/stores_decorator.rb
Spree::Store.class_eval do
  validates_numericality_of :number_of_hours_allowed_before_placing_order, greater_than_or_equal_to: 0, allow_blank: true
  has_many :working_days

  def currently_open?
    todays_name = DateTime.now.utc.strftime("%A")
    working_day = working_days.where(name: todays_name).first

    if working_day.present?
      working_day.currently_operating?
    else
      false
    end
  end

  def currently_closed?
    !currently_open?
  end

  def closest_working_date_and_time
    current_datetime = DateTime.now.utc
    current_datetime = current_datetime.change(hour: 0, minute: 0, second: 0)
    todays_name = current_datetime.strftime("%A")
    sorted_days_from_today = DateTime::DAYNAMES.rotate(DateTime::DAYNAMES.index(todays_name))

    if currently_open?
      return DateTime.now.utc.round_off(15.minutes)
    else
      wds = working_days.includes(:working_hours)

      sorted_days_from_today.each do |day_name|
        wd = wds.find_by(name: day_name)

        if wd.present?

          while current_datetime.strftime("%A") != day_name do
            current_datetime = current_datetime.next_day;
          end

          while current_datetime.strftime("%A") == day_name do
            return current_datetime if wd.can_operate?(current_datetime)
            current_datetime += 15.minutes
          end
        end
      end
    end

    nil
  end
end

app/models/spree/working_day.rb
class Spree::WorkingDay < Spree::Base
  belongs_to :store
  has_many :working_hours, dependent: :destroy
  validates :name, presence: true
  # ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
  validates :name, inclusion: { in: Date::DAYNAMES, message: "Allowed names are #{Date::DAYNAMES}" }

  def currently_operating?
    can_operate?(DateTime.now.utc)
  end

  def can_operate?(datetime)
    hours_threshold = store.number_of_hours_allowed_before_placing_order ? store.number_of_hours_allowed_before_placing_order.hours : 0

    working_hours.each do |wh|
      wh_difference = wh.end_time - wh.start_time
      wh_start_time = wh.start_time.change(year: datetime.year, day: datetime.day, month: datetime.month)
      wh_end_time = wh_start_time + wh_difference

      if (datetime >= wh_start_time && datetime <= wh_end_time)
        if (datetime - hours_threshold + 1.minute >= DateTime.now.utc)
          return true
        end
      end
    end

    false
  end

  def description
    return "No working hours available" if working_hours.blank?
    working_hours.map{ |wh| "#{wh.start_time.to_s(:hour_minute_am_pm)} - #{wh.end_time.to_s(:hour_minute_am_pm)}"}.to_sentence
  end
end

app/models/spree/working_hour.rb
class Spree::WorkingHour < Spree::Base
  belongs_to :working_day
  validates :start_time, :end_time, presence: true
  validate :validate_interval
  default_scope { order(start_time: :asc, end_time: :asc) }

  def validate_interval
    if end_time.present? && start_time.present?
      errors.add(:base, "End time should be greater than start time") if end_time <= start_time
    else
      errors.add(:base, "End & start time should be present")
    end
  end
end

app/models/time_decorator.rb
require 'active_support/core_ext/numeric' # from gem 'activesupport'

class Time
  # Time#round already exists with different meaning in Ruby 1.9
  def round_off(seconds = 60)
    Time.at((self.to_f / seconds).round * seconds).utc
  end

  def floor(seconds = 60)
    Time.at((self.to_f / seconds).floor * seconds).utc
  end
end

app/controllers/spree/admin/working_days_controller.rb
class Spree::Admin::WorkingDaysController < Spree::Admin::BaseController
  before_action :load_store

  def index
  end

  def create
    working_day = @store.working_days.new(working_day_params)
    flash[:error] = working_day.errors.full_messages.join(", ") if !working_day.save
    redirect_to admin_store_working_days_path(@store)
  end

  def edit
    @working_day = @store.working_days.where(id: params[:id]).first
  end

  def destroy
    @store.working_days.where(id: params[:id]).first.try(:destroy)
    redirect_to admin_store_working_days_path(@store)
  end

  private
  def load_store
    @store = Spree::Store.find_by(id: params[:store_id])

    if @store.blank?
      flash[:error] = "Store not found"
      redirect_to admin_path
    end
  end

  def working_day_params
    params.require(:working_day).permit(:name)
  end
end

app/controllers/spree/admin/working_days_controller_decorator.rb
class Spree::Admin::WorkingDaysController < Spree::Admin::BaseController
  before_action :load_store

  def index
  end

  def create
    working_day = @store.working_days.new(working_day_params)
    flash[:error] = working_day.errors.full_messages.join(", ") if !working_day.save
    redirect_to admin_store_working_days_path(@store)
  end

  def edit
    @working_day = @store.working_days.where(id: params[:id]).first
  end

  def destroy
    @store.working_days.where(id: params[:id]).first.try(:destroy)
    redirect_to admin_store_working_days_path(@store)
  end

  private
  def load_store
    @store = Spree::Store.find_by(id: params[:store_id])

    if @store.blank?
      flash[:error] = "Store not found"
      redirect_to admin_path
    end
  end

  def working_day_params
    params.require(:working_day).permit(:name)
  end
end

app/controllers/spree/admin/working_hours_controller.rb
class Spree::Admin::WorkingHoursController < Spree::Admin::BaseController
  before_action :load_store_and_working_day

  def create
    working_hour = @working_day.working_hours.new(working_hours_params)

    if !working_hour.save
      flash[:error] = working_hour.errors.full_messages.join(", ")
    end

    redirect_to edit_admin_store_working_day_path(@store, @working_day)
  end

  def update
    working_hour = @working_day.working_hours.where(id: params[:id])

    if working_hour.present?
      flash[:error] = working_hour.errors.full_messages.join(",") if !working_hour.update(working_hours_params)
    end

    redirect_to edit_admin_store_working_day_path(@store, @working_day)
  end

  def destroy
    working_hour = @working_day.working_hours.where(id: params[:id]).first
    working_hour.try(:destroy)
    redirect_to edit_admin_store_working_day_path(@store, @working_day)
  end

  private

  def load_store_and_working_day
    @store = Spree::Store.find_by(id: params[:store_id])
    @working_day = @store.working_days.where(id: params[:working_day_id]).first

    if @store.blank? || @working_day.blank?
      redirect_to admin_path
    end
  end

  def working_hours_params
    params[:working_hour].permit(:start_time, :end_time, :description)
  end
end

app/controllers/spree/admin/working_hours_controller_decorator.rb
class Spree::Admin::WorkingHoursController < Spree::Admin::BaseController
  before_action :load_store_and_working_day

  def create
    working_hour = @working_day.working_hours.new(working_hours_params)

    if !working_hour.save
      flash[:error] = working_hour.errors.full_messages.join(", ")
    end

    redirect_to edit_admin_store_working_day_path(@store, @working_day)
  end

  def update
    working_hour = @working_day.working_hours.where(id: params[:id])

    if working_hour.present?
      flash[:error] = working_hour.errors.full_messages.join(",") if !working_hour.update(working_hours_params)
    end

    redirect_to edit_admin_store_working_day_path(@store, @working_day)
  end

  def destroy
    working_hour = @working_day.working_hours.where(id: params[:id]).first
    working_hour.try(:destroy)
    redirect_to edit_admin_store_working_day_path(@store, @working_day)
  end

  private

  def load_store_and_working_day
    @store = Spree::Store.find_by(id: params[:store_id])
    @working_day = @store.working_days.where(id: params[:working_day_id]).first

    if @store.blank? || @working_day.blank?
      redirect_to admin_path
    end
  end

  def working_hours_params
    params[:working_hour].permit(:start_time, :end_time, :description)
  end
end

app/helpers/spree/admin/working_days_helper.rb
module Spree::Admin::WorkingDaysHelper
end

app/helpers/spree/admin/working_hours_helper.rb
module Spree::Admin::WorkingHoursHelper
end

app/views/spree/admin/working_days/edit.html.haml
= render 'spree/admin/shared/general_tabs'

.working_hours#edit
  .container
    %h1= @working_day.name
    %h4= "- #{@working_day.description}"
    %span#local_time= ""
    .row
      .col-1= "#"
      .col-3= "Start time"
      .col-3= "End Time"
      .col-3= "Description"
      .col-2= ""

    - @working_day.working_hours.each_with_index do |wh, index|
      = form_for (wh), url: admin_store_working_day_working_hour_path(@store, @working_day, wh) do |f|
        .row
          .col-1= index + 1
          .col-3
            %input.timestamp{target: "working_hour[start_time]"}
            = f.hidden_field :start_time, value: wh.start_time.to_f * 1000
          .col-3
            %input.timestamp{target: "working_hour[end_time]"}
            = f.hidden_field :end_time, value: wh.end_time.to_f * 1000
          .col-3= f.text_field :description
          .col-2
            = f.submit "Update", class: "btn btn-warning"
            = link_to "Destroy", admin_store_working_day_working_hour_path(@store.id, @working_day, wh.id), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure ?"}
    %br
    %br
    = form_for @working_day.working_hours.new, url: admin_store_working_day_working_hours_path(@store, @working_day) do |f|
      = f.label :start_time
      %input.timestamp{target: "working_hour[start_time]"}
      = f.hidden_field :start_time
      %br
      = f.label :end_time
      %input.timestamp{target: "working_hour[end_time]"}
      = f.hidden_field :end_time
      %br
      = f.label :description
      = f.text_field :description, placeholder: "Will be shown instead of hour."
      = f.submit :add

:javascript

  Spree.ready(function() {
    $("input.timestamp").map(function(el){
      let this_form = $(this).closest("form")
      let this_input = $(this)
      let target_name = this_input[0].attributes["target"].value
      let input_name = `input[name='${target_name}']`
      let input_obj = this_form.find(input_name)
      let val_ms = this_form.find(input_name).val()
      let old_date = new Date(parseInt(val_ms))

      if (isNaN(old_date))
        old_date = new Date()

      input_obj.val(old_date)

      $(this).flatpickr({
        enableTime: true,
        noCalendar: true,
        time_24hr: true,
        defaultDate: old_date,
        onChange: function(date) {
          input_obj.val(date[0])
        }
      })
    })
  })

app/views/spree/admin/working_days/index.html.haml
= render 'spree/admin/shared/general_tabs'

.working_days#index
  .container
    - @store.working_days.each_with_index do |wd, index|
      .row
        .col-1= index + 1
        .col-2= wd.name
        .col-6= wd.description
        .col-3
          = link_to "Edit", edit_admin_store_working_day_path(@store.id, wd.id), class: "btn btn-warning"
          = link_to "Destroy", admin_store_working_day_path(@store.id, wd.id), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure ?"}
    %br
    %br  
    = form_for [:admin, :store, @store.working_days.new] do |f|
      = f.label :day_name
      = f.select :name, Date::DAYNAMES - @store.working_days.map(&:name)
      = f.submit :add

    = form_for [:admin, @store] do |f|
      = f.label :number_of_hours_allowed_before_placing_order
      = f.number_field :number_of_hours_allowed_before_placing_order, step: 0.5
      = f.submit :update, class: "btn btn-warning"
    %br